Fix sanity pylint (#44)
* sanity: fix pylint ansible-format-automatic-specification

ERROR: plugins/cliconf/arubaoss.py:50:39: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/arubaoss.py:117:20: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/arubaoss.py:252:20: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/arubaoss.py:349:39: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_acl_policy.py:305:33: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_acl_policy.py:320:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_acl_policy.py:332:37: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_acl_policy.py:487:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_config_bkup.py:233:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_interface.py:139:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_interface.py:189:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_interface.py:253:25: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_ip_route.py:172:31: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_ip_route.py:182:27: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_ip_route.py:212:27: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_loop_protect.py:141:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_loop_protect.py:162:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_ntp.py:457:27: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_ntp.py:562:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_qos_policy.py:135:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_qos_policy.py:146:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_snmp.py:275:27: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_traffic_class.py:229:51: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_traffic_class.py:238:51: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_user.py:111:31: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_vlan.py:282:35: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_vlan.py:437:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_vlan.py:489:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_vlan.py:537:23: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/modules/arubaoss_vlan.py:540:17: ansible-format-automatic-specification: Format string contains automatic field numbering specification

* sanity: fix pylint ansible-bad-function

plugins/modules/arubaoss_acl_policy.py:363:16: ansible-bad-function: Call module.log or module.debug instead of builtins.print
plugins/modules/arubaoss_ip_auth.py:136:16: ansible-bad-function: Call module.log or module.debug instead of builtins.print
plugins/modules/arubaoss_traffic_class.py:344:12: ansible-bad-function: Call module.log or module.debug instead of builtins.print
plugins/modules/arubaoss_traffic_class.py:346:12: ansible-bad-function: Call module.log or module.debug instead of builtins.print

* port_rate_limit: fix sanity pylint multiple-imports

plugins/modules/arubaoss_port_rate_limit.py:119:0: multiple-imports: Multiple imports on one line (sys, json)

* config_bkup: fix sanity pylint disallowed-name

plugins/modules/arubaoss_config_bkup.py:221:8: disallowed-name: Disallowed name _

* arubaoss(cliconf): fix sanity pylint dangerous-default-value

plugins/module_utils/arubaoss.py:119:4: dangerous-default-value: Dangerous default value {} as argument
plugins/module_utils/arubaoss.py:254:4: dangerous-default-value: Dangerous default value {} as argument
plugins/module_utils/arubaoss.py:294:4: dangerous-default-value: Dangerous default value {} as argument

* traffic_class: fix sanity pylint unnecessary-comprehension

arubaoss_traffic_class.py:377:0: unnecessary-comprehension: Unnecessary use of a comprehension, use list(range(0, 64)) instead